"""Shared strategy primitives."""

from .filtering import (
    CORE_FILTER_STEP_NAMES,
    STYLE_STRUCTURAL_STEP_NAMES,
    apply_filters_with_diagnostics,
    apply_scored_or_hard_filters,
    classify_filter_step_layer,
    first_fail_concentration,
    near_miss_concentration,
    partition_filter_steps,
    summarize_diagnostics_by_layer,
    summarize_first_fail_reasons,
)
from .research import (
    apply_low_value_research_gate,
    apply_research_assessment,
    apply_triage_labels,
    assign_triage_label,
    build_research_assessment,
    metric_float,
    text_has_any,
)
from .rules import (
    HIGH_COVERAGE_HARD_FILTER_METRICS,
    LOW_COVERAGE_HARD_FILTER_METRICS,
    MEDIUM_COVERAGE_HARD_FILTER_METRICS,
    append_professional_filter_steps,
    build_benchmark_trend_step,
    build_filter_steps,
    build_industry_trend_steps,
    build_momentum_steps,
    channel_bucket_mask,
    hard_filter_metric_enabled,
    passes_sic_filters,
    percentile_cap_mask,
    percentile_floor_mask,
    watchlist_member_mask,
)
from .scoring import robust_normalize_score, score_and_rank
from .selection import (
    apply_group_caps,
    dedupe_symbol_by_best_channel,
    drop_symbols,
    normalize_symbol_list,
    select_symbols_from_ranked_frames,
)

__all__ = [
    "CORE_FILTER_STEP_NAMES",
    "HIGH_COVERAGE_HARD_FILTER_METRICS",
    "LOW_COVERAGE_HARD_FILTER_METRICS",
    "MEDIUM_COVERAGE_HARD_FILTER_METRICS",
    "STYLE_STRUCTURAL_STEP_NAMES",
    "append_professional_filter_steps",
    "apply_filters_with_diagnostics",
    "apply_group_caps",
    "apply_low_value_research_gate",
    "apply_research_assessment",
    "apply_scored_or_hard_filters",
    "apply_triage_labels",
    "assign_triage_label",
    "build_benchmark_trend_step",
    "build_filter_steps",
    "build_industry_trend_steps",
    "build_momentum_steps",
    "build_research_assessment",
    "channel_bucket_mask",
    "classify_filter_step_layer",
    "dedupe_symbol_by_best_channel",
    "drop_symbols",
    "first_fail_concentration",
    "hard_filter_metric_enabled",
    "metric_float",
    "near_miss_concentration",
    "normalize_symbol_list",
    "partition_filter_steps",
    "passes_sic_filters",
    "percentile_cap_mask",
    "percentile_floor_mask",
    "robust_normalize_score",
    "score_and_rank",
    "select_symbols_from_ranked_frames",
    "summarize_diagnostics_by_layer",
    "summarize_first_fail_reasons",
    "text_has_any",
    "watchlist_member_mask",
]
